#!/usr/bin/env python3
"""Build a private Kaggle CPU kernel (script + metadata) that carries src/tsb, scripts, configs, the service skeleton (no weights) and
the public-domain assets, and runs scripts/kdriver.py <plan> inside Kaggle.   Nothing is pushed here.
usage: python scripts/make_kernel.py <plan: a1|a2|b> [--slug bench-timeseries-<x>] [--with-ref] [--sources slug,slug]
--with-ref embeds the Mac v0 dev checkpoint + its VAL-F per-round file + the dev report (a1 reproducibility gate; binary, so the generated
kaggle/ directory is gitignored).  The b plan refuses to build from a dirty tracked tree (TEST-F code must be the committed code)."""
import argparse, base64, io, json, os, subprocess, sys, tarfile, time

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def git(*a):
    return subprocess.run(["git", "-C", ROOT, *a], capture_output=True, text=True).stdout.strip()

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("plan"); ap.add_argument("--slug", default=None); ap.add_argument("--with-ref", action="store_true")
    ap.add_argument("--sources", default="")
    a = ap.parse_args()
    slug = a.slug or f"bench-timeseries-{a.plan}"
    dirty = [l for l in git("status", "--porcelain", "--untracked-files=no").splitlines() if l.strip()]
    if a.plan == "b" and dirty:
        sys.exit("refusing to build the TEST-F kernel from a dirty tree: " + "; ".join(dirty[:5]))
    build = dict(plan=a.plan, slug=slug, commit=git("rev-parse", "HEAD"), dirty_tracked_files=dirty, built_utc=time.strftime("%Y-%m-%d %H:%M:%S", time.gmtime()))
    files = []
    def add(rel):
        files.append(rel)
    for d, exts in (("src/tsb", (".py",)), ("scripts", (".py",)), ("configs", (".json",)), ("assets", (".npz", ".json"))):
        for f in sorted(os.listdir(os.path.join(ROOT, d))):
            if f.endswith(exts) and os.path.isfile(os.path.join(ROOT, d, f)):
                add(f"{d}/{f}")
    svc = "submission/model-services/gridload-compact"
    for dp, dn, fn in os.walk(os.path.join(ROOT, svc)):
        dn[:] = [x for x in dn if x not in ("weights", "__pycache__", ".pytest_cache")]
        for f in fn:
            add(os.path.relpath(os.path.join(dp, f), ROOT))
    add("TEST-LOG.md")
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz") as t:
        for rel in files:
            t.add(os.path.join(ROOT, rel), arcname=rel)
        if a.with_ref:                     # everything under assets/ref (gitignored): Mac v0 checkpoint + its per-round file, the dev report, the Mac field caches, expected hashes
            for f in sorted(os.listdir(os.path.join(ROOT, "assets", "ref"))):
                t.add(os.path.join(ROOT, "assets", "ref", f), arcname=f"assets/ref/{f}")
        bj = json.dumps(build, indent=1).encode()
        ti = tarfile.TarInfo("BUILD.json"); ti.size = len(bj); ti.mtime = int(time.time()); t.addfile(ti, io.BytesIO(bj))
    payload = base64.b64encode(buf.getvalue()).decode()
    script = f'''# generated by scripts/make_kernel.py: plan {a.plan}, commit {build["commit"][:10]}, built {build["built_utc"]} UTC.  Private kernel, CPU only.
import base64, io, os, runpy, sys, tarfile
PAYLOAD = (
{chr(10).join(repr(payload[i:i+4000]) for i in range(0, len(payload), 4000))}
)
REPO = "/tmp/repo"
os.makedirs(REPO, exist_ok=True)
tarfile.open(fileobj=io.BytesIO(base64.b64decode("".join(PAYLOAD))), mode="r:gz").extractall(REPO)
os.environ.update(TSB_ROOT=REPO, TSB_KERNEL="{slug}", TSB_COMMIT="{build["commit"]}")
sys.argv = ["kdriver.py", "{a.plan}"]
runpy.run_path(os.path.join(REPO, "scripts", "kdriver.py"), run_name="__main__")
'''
    out = os.path.join(ROOT, "kaggle", slug); os.makedirs(out, exist_ok=True)
    open(os.path.join(out, "script.py"), "w").write(script)
    meta = dict(id=f"sankalpsthakur/{slug}", title=slug, code_file="script.py", language="python", kernel_type="script", is_private="true",
                enable_gpu="false", enable_tpu="false", enable_internet="true", dataset_sources=[], competition_sources=[],
                kernel_sources=[s for s in a.sources.split(",") if s], model_sources=[])
    json.dump(meta, open(os.path.join(out, "kernel-metadata.json"), "w"), indent=2)
    print(f"built {out} ({len(files)} files, payload {len(payload)/1e3:.0f} kB, commit {build['commit'][:10]}, dirty={len(dirty)})")

if __name__ == "__main__":
    main()
